name: iOS

on:
  push:
	branches: [ "main" ]
  pull_request:
	branches: [ "main" ]

jobs:
  build:
	runs-on: macos-latest

	steps:
	- uses: actions/checkout@v3
	- name: Build
	  run: >
	  	xcodebuild -scheme Cache -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 14 Pro'
	- name: Run tests
	  run: >
	  	xcodebuild test -workspace .swiftpm/xcode/package.xcworkspace -scheme Cache -sdk iphoneos -destination "platform=iOS Simulator,OS=17.0,name=iPhone 14 Pro" CODE_SIGNING_ALLOWED=No